### PR TITLE
tea.yaml

### PR DESCRIPTION
**Pull request by AniesXYZ**

### CODE REVIEW

**Comment by reorx** [comment]
What is this? Are you trying to register this project on tea.xyz?

**Comment by AniesXYZ** [comment]
Ya bro

Pada Sab, 24 Feb 2024 09.25, Xiao Meng ***@***.***> menulis:

**Comment by aredridel** [comment]
Hey! Just a heads up, this PR is probably spam — some discussion [here](https://kolektiva.social/@aredridel/111998475796358898) and [here](https://github.com/aredridel/node-bin-gen/pull/241#issuecomment-1963442116)

**Comment by reorx** [comment]
@aredridel yeah I already know through https://news.ycombinator.com/item?id=39510756, anyway thanks for remind

**Pull request closed without merging**
